### ISSUE TITLE
When will capacitor 5 be compatible?

### ISSUE THREAD

**Issue by Dangerous828** [rabianr/capacitor-line-login#1]
When will capacitor 5 be compatible? Are there any more updates planned?

Because now installing this package directly in capacitor gives an error that it can't be installed.

npm install capacitor-line-login -S
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: coke-shoppo-app@0.0.1
npm ERR! Found: @capacitor/core@5.5.1
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"5.5.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^4.0.0" from capacitor-line-login@0.0.3
npm ERR! node_modules/capacitor-line-login
npm ERR!   capacitor-line-login@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! 
npm ERR! For a full report see:
npm ERR! C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-12-19T09_35_28_078Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-12-19T09_35_28_078Z-debug-0.log

**Comment by rabianr** [comment]
I added support for capacitor v5. You can try the newest version.

**Comment by Dangerous828** [comment]
Yes, I can use it properly in capacitor 5, thanks a lot!
